services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app

  postgres:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr3s
      - POSTGRES_DB=inmobiliaria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
