name: TFG-IDEALISTA
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  # Análisis de datos
  - pandas=1.5.3
  - numpy=1.26.4
  - scikit-learn=1.2.2
  - scipy=1.15.1
  - statsmodels=0.14.1
  - joblib=1.3.2
  - threadpoolctl=3.5.0

  # Visualización
  - matplotlib=3.5.3
  - seaborn=0.13.2
  - plotly=5.20.0

  # Datos geoespaciales
  - geopandas=0.14.3
  - folium=0.15.1
  - shapely=2.0.3
  - pyproj=3.6.1
  - pyogrio=0.6.2
  - mapclassify=2.6.1

  # Base de datos
  - psycopg2=2.9.9

  # Redes
  - networkx=3.2.1

  # Otros
  - protobuf=5.29.3
  - tornado=6.3.3
  - typing_extensions=4.9.0
  - tzdata=2024a

  # Dependencias pip
  - pip:
      - django==5.1.5
      - djangorestframework==3.15.2
      - django-cors-headers==4.6.0
      - streamlit==1.41.1
      - xgboost==1.7.6
      - git+https://github.com/jakobrunge/tigramite.git
